#!/bin/sh
# Arch post install script.
# Run this script after entering chroot environment.

pacman -S grub
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

echo "Generating locale"
sed -i 's/#en_US/en_US/g' /etc/locale.gen
locale-gen
clear

echo "Setting up timezone"
ln -sf /usr/share/zoneinfo/Asia/Dhaka /etc/localtime
hwclock --systohc --utc

echo "Setting up hostname"
echo "arch" > /etc/hostname

pacman -S networkmanager cronie 
echo "Enabling sevices"
systemctl enable NetworkManager
systemctl enable cronie

echo "Adding user antu to the system"
useradd -G wheel -s /bin/bash antu

if [ -d /home/antu ]; then
	
	chown -R antu:wheel /home/antu
else
	mkdir /home/antu
	chown -R antu:wheel /home/antu
fi
clear

echo "Making pacman & yay more colorful"
grep "^Color" /etc/pacman.conf >/dev/null || sed -i "s/^#Color/Color/" /etc/pacman.conf
grep "ILoveCandy" /etc/pacman.conf >/dev/null || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
sed -i "s/^#VerbosePkgLists/VerbosePkgLists/" /etc/pacman.conf

echo "Enabling Use all cores for compilation."
sed -i "s/-j2/-j$(nproc)/;s/^#MAKEFLAGS/MAKEFLAGS/" /etc/makepkg.conf

